// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzzsOKqVrzdR_Q1zgRbMzNSEv9-dbl2b4',
    appId: '1:793442032814:web:63445d22991ca8e64d613f',
    messagingSenderId: '793442032814',
    projectId: 'photo-sharing-clone-app-9eacf',
    authDomain: 'photo-sharing-clone-app-9eacf.firebaseapp.com',
    storageBucket: 'photo-sharing-clone-app-9eacf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkVN96LazlGKyAWmXtMXuIde0sECblgI4',
    appId: '1:793442032814:android:931c020c83a833e64d613f',
    messagingSenderId: '793442032814',
    projectId: 'photo-sharing-clone-app-9eacf',
    storageBucket: 'photo-sharing-clone-app-9eacf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxjXvXXOAi2Nf2cKTpxWleIwIKoFo8kj0',
    appId: '1:793442032814:ios:58e60d8c5d94b15f4d613f',
    messagingSenderId: '793442032814',
    projectId: 'photo-sharing-clone-app-9eacf',
    storageBucket: 'photo-sharing-clone-app-9eacf.appspot.com',
    iosClientId: '793442032814-bkm9uer0rh5ddht9t76phnvs4vrmqrad.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinterestCloneCodingcafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxjXvXXOAi2Nf2cKTpxWleIwIKoFo8kj0',
    appId: '1:793442032814:ios:58e60d8c5d94b15f4d613f',
    messagingSenderId: '793442032814',
    projectId: 'photo-sharing-clone-app-9eacf',
    storageBucket: 'photo-sharing-clone-app-9eacf.appspot.com',
    iosClientId: '793442032814-bkm9uer0rh5ddht9t76phnvs4vrmqrad.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinterestCloneCodingcafe',
  );
}
